version: '3'
services:
  mySQL:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_USER : root
      MYSQL_ROOT_PASSWORD : password
      MYSQL_DATABASE : Intern
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:80
volumes:
  db: